### ISSUE TITLE
Large export size difference between online and offline tool

### ISSUE THREAD

**Issue by vdveen** [hotosm/osm-export-tool-python#15]
Using the Geofabrik country PBFs, I get very different results with the offline tool vs the online tool. Here is the [online run that I did](https://export.hotosm.org/en/v3/exports/3782f93c-9549-4694-b35b-63c5d224b5fe), resulting in a 191MB shapefile set. Below the output of the command line tool with the exact same GeoJSON and YAML files used, resulting in a total file set size of 446MB:

```sh
overmorgen_anne@Delft:~/osm_export$ osm-export-tool osm_inputs/HU-latest.osm.pbf outputs/budapest-test-tool.shp -f shp -m export.yaml --clip nuts_geb_json/nuts_id_HU110.geojson

Warning: using first feature of --clip FeatureCollection.
Invalid area: 2536013
Invalid area: 732151021
Completed in 314.15604853630066 seconds.
shp planet_osm_point outputs/budapest-test-tool.shp_planet_osm_point.shp,outputs/budapest-test-tool.shp_planet_osm_point.shx,outputs/budapest-test-tool.shp_planet_osm_point.prj,outputs/budapest-test-tool.shp_planet_osm_point.cpg,outputs/budapest-test-tool.shp_planet_osm_point.dbf 34.57MB
shp planet_osm_polygon outputs/budapest-test-tool.shp_planet_osm_polygon.shp,outputs/budapest-test-tool.shp_planet_osm_polygon.shx,outputs/budapest-test-tool.shp_planet_osm_polygon.prj,outputs/budapest-test-tool.shp_planet_osm_polygon.cpg,outputs/budapest-test-tool.shp_planet_osm_polygon.dbf 364.54MB
shp planet_osm_line outputs/budapest-test-tool.shp_planet_osm_line.shp,outputs/budapest-test-tool.shp_planet_osm_line.shx,outputs/budapest-test-tool.shp_planet_osm_line.prj,outputs/budapest-test-tool.shp_planet_osm_line.cpg,outputs/budapest-test-tool.shp_planet_osm_line.dbf 46.01MB
```

Looking at the data that these methods produce, I can't seem to find out why the offline shapefile is so much larger. The layers look nearly identical when plotted in QGIS, both have ~128k records in the polygon layer. The online (smaller in size) shp even has two additional columns (z-index & osm_way_id). There are some minor differences, like additional residential areas and changes in building footprints, but these cannot account for the 3x size difference. 

[Here is the GeoJSON](https://github.com/hotosm/osm-export-tool-python/files/3787914/nuts_id_HU110.txt), [here is the YAML used](https://github.com/hotosm/osm-export-tool-python/files/3787916/export.txt).

**Comment by bdon** [comment]
@vdveen the online tool is not using this code yet.

export-staging.hotosm.org is running the newer code in this repo, I should have export.hotosm.org updated within the next week or so.

The layers should be almost identical, but the newer code should be more correct. The old code that results in the larger file depends on the OGR OSM driver, which uses intermediate tables called "point", "linestring", "multi polygon" to do the conversion. This accounts for the large size difference because those tables aren't cleaned up. The new code does not use the OGR OSM driver so does not have any intermediate tables.

**Comment by vdveen** [comment]
Great! Does that mean I can reinstall the command line tool and it should be lower in size?

**Comment by bdon** [comment]
Oh, I think I got it backwards. The offline shapefile should be smaller, not larger. I'll need to investigate that. It may possibly be due to padding in one of the shapefile components. 

Is there a reason you need to stick to Shapefile instead of using Geopackage?

**Comment by bdon** [comment]
@vdveen can you try installing 0.0.17 ? The issue was that the default String field width in the old code was 80, and the new was 254. I changed the new code back to 80, so the .dbf file should be 1/3 the size before.

**Comment by vdveen** [comment]
It worked! I ran the same code as the one in the issue opener, and it ran faster and more compact with the 0.0.17 build installed: 

```sh
osm-export-tool osm_inputs/HU-latest.osm.pbf outputs/budapest-test-tool-17.shp -f shp -m expo
rt.yaml --clip nuts_geb_json/nuts_id_HU110.geojson
Warning: using first feature of --clip FeatureCollection.
Invalid area: 2536013
Invalid area: 732151021
Completed in 168.96525526046753 seconds.
shp {'theme': 'planet_osm_point'} outputs/budapest-test-tool-17.shp_planet_osm_point_points.shp,outputs/budapest-test-tool-17.shp_planet_osm_point_points.shx,outputs/budapest-test-tool-17.shp_planet_osm_point_points.prj,outputs/budapest-test-tool-17.shp_planet_osm_point_points.cpg,outputs/budapest-test-tool-17.shp_planet_osm_point_points.dbf 11.26MB
shp {'theme': 'planet_osm_polygon'} outputs/budapest-test-tool-17.shp_planet_osm_polygon_polygons.shp,outputs/budapest-test-tool-17.shp_planet_osm_polygon_polygons.shx,outputs/budapest-test-tool-17.shp_planet_osm_polygon_polygons.prj,outputs/budapest-test-tool-17.shp_planet_osm_polygon_polygons.cpg,outputs/budapest-test-tool-17.shp_planet_osm_polygon_polygons.dbf 131.27MB
shp {'theme': 'planet_osm_line'} outputs/budapest-test-tool-17.shp_planet_osm_line_lines.shp,outputs/budapest-test-tool-17.shp_planet_osm_line_lines.shx,outputs/budapest-test-tool-17.shp_planet_osm_line_lines.prj,outputs/budapest-test-tool-17.shp_planet_osm_line_lines.cpg,outputs/budapest-test-tool-17.shp_planet_osm_line_lines.dbf 21.93MB
```
